sudo: required
language: node_js
node_js: '8'
git:
  depth: 1
cache:
  yarn: true
  directories:
  - node_modules
script:
- yarn
deploy:
  provider: releases
  api_key: $GITHUB_RELEASE_TOKEN
  file: dist/electron-ide-*-x86_64.AppImage
  skip_cleanup: true
  on:
    tags: true
